### ISSUE TITLE
Q4 Milestone Tracking

### ISSUE THREAD

**Issue by samlaf** [Layr-Labs/eigensdk-go#36]
Issue to track deliverables we want to ship for Q4

```[tasklist]
### Tasks
- [ ] https://github.com/Layr-Labs/eigensdk-go/pull/24
- [ ] https://github.com/Layr-Labs/eigensdk-go/issues/26
- [ ] https://github.com/Layr-Labs/eigensdk-go/issues/37
- [ ] https://github.com/Layr-Labs/eigensdk-go/issues/38
- [ ] https://github.com/Layr-Labs/eigensdk-go/issues/39
- [ ] https://github.com/Layr-Labs/eigensdk-go/issues/40
- [ ] https://github.com/Layr-Labs/eigensdk-go/issues/41
```

**Comment by samlaf** [comment]
Closing as no longer relevant.
